### ISSUE TITLE
pyspark load read stream error

### ISSUE THREAD

**Issue by abhishekpoonia31** [googleapis/java-pubsublite-spark#257]
Hi, I'm getting the below error while using pubsub lite in pyspark.
**Package**: com.google.cloud:pubsublite-spark-sql-streaming:0.3.1

**Environment**:
![image](https://user-images.githubusercontent.com/591155/131306786-2c954291-24a6-46cf-9f86-cb884b2df9ca.png)

**Error Log**:

`---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-5-c732b853abe1> in <module>
      2 df = spark.readStream \
      3             .format("pubsublite") \
----> 4             .option("pubsublite.subscription", "projects/234242/locations/us-central1-c/subscriptions/subscription") \
      5             .load()

/usr/lib/spark/python/pyspark/sql/streaming.py in load(self, path, format, schema, **options)
    398             return self._df(self._jreader.load(path))
    399         else:
--> 400             return self._df(self._jreader.load())
    401 
    402     @since(2.0)

/opt/conda/anaconda/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/conda/anaconda/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o203.load.
: com.google.api.gax.rpc.ApiException: 
	at com.google.cloud.pubsublite.internal.CheckedApiException.<init>(CheckedApiException.java:51)
	at com.google.cloud.pubsublite.internal.CheckedApiException.<init>(CheckedApiException.java:55)
	at com.google.cloud.pubsublite.internal.ExtractStatus.toCanonical(ExtractStatus.java:48)
	at com.google.cloud.pubsublite.spark.PslDataSource.createMicroBatchReader(PslDataSource.java:100)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
	at io.grpc.Metadata$Key.validateName(Metadata.java:742)
	at io.grpc.Metadata$Key.<init>(Metadata.java:750)
	at io.grpc.Metadata$Key.<init>(Metadata.java:668)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:959)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:954)
	at io.grpc.Metadata$Key.of(Metadata.java:705)
	at io.grpc.Metadata$Key.of(Metadata.java:701)
	at com.google.api.gax.grpc.GrpcHeaderInterceptor.<init>(GrpcHeaderInterceptor.java:60)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:311)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1800(InstantiatingGrpcChannelProvider.java:82)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:237)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:247)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:225)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:205)
	at com.google.cloud.pubsublite.v1.stub.GrpcAdminServiceStub.create(GrpcAdminServiceStub.java:310)
	at com.google.cloud.pubsublite.v1.stub.AdminServiceStubSettings.createStub(AdminServiceStubSettings.java:591)
	at com.google.cloud.pubsublite.v1.AdminServiceClient.<init>(AdminServiceClient.java:174)
	at com.google.cloud.pubsublite.v1.AdminServiceClient.create(AdminServiceClient.java:155)
	at com.google.cloud.pubsublite.spark.PslReadDataSourceOptions.newAdminServiceClient(PslReadDataSourceOptions.java:192)
	at com.google.cloud.pubsublite.spark.PslReadDataSourceOptions.newAdminClient(PslReadDataSourceOptions.java:206)
	at com.google.cloud.pubsublite.spark.PslDataSource.createMicroBatchReader(PslDataSource.java:97)
	... 12 more`

**pip freeze**:
arrow==1.1.1
asn1crypto==1.0.1
astroid==2.3.1
astropy==3.2.2
async-generator==1.10
async-timeout==3.0.1
asyncio==3.4.3
atomicwrites==1.3.0
attrs==21.2.0
Babel==2.7.0
backcall==0.1.0
backports.functools-lru-cache==1.5
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
bcolz==1.2.1
beautifulsoup4==4.8.0
binaryornot==0.4.4
bitarray==1.0.1
bkcharts==0.2
black==21.7b0
bleach==3.1.0
blinker==1.4
bokeh==1.3.4
boto==2.49.0
Bottleneck==1.2.1
bs4==0.0.1
cachetools==4.2.2
certifi==2019.9.11
certipy==0.1.3
cffi==1.12.3
chardet==3.0.4
charset-normalizer==2.0.4
Click==7.0
cloudpickle==1.2.2
clyent==1.2.2
colorama==0.4.1
conda==4.7.12
conda-build==3.18.9
conda-package-handling==1.6.0
conda-verify==3.4.2
confuse==1.4.0
contextlib2==0.6.0
cookiecutter==1.7.3
cryptography==2.7
cycler==0.10.0
Cython==0.29.13
cytoolz==0.10.0
dask==2.5.2
decorator==4.4.0
defusedxml==0.6.0
distlib==0.3.2
distributed==2.5.2
docker==5.0.0
docutils==0.15.2
entrypoints==0.3
et-xmlfile==1.0.1
fairing==0.5.3
fastcache==1.1.0
filelock==3.0.12
findspark==1.3.0
Flask==1.1.1
fsspec==2021.7.0
future==0.17.1
gcsfs==2021.7.0
gevent==1.4.0
gitdb==4.0.7
GitPython==3.1.18
glob2==0.7
gmpy2==2.0.8
google-api-core==1.31.2
google-api-python-client==1.11.0
google-auth==1.35.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.5
google-cloud-bigquery==1.26.1
google-cloud-bigquery-storage==1.0.0
google-cloud-core==1.4.4
google-cloud-dataproc==1.1.1
google-cloud-datastore==1.15.3
google-cloud-language==1.3.0
google-cloud-logging==1.15.1
google-cloud-pubsub==2.7.1
google-cloud-pubsublite==1.1.0
google-cloud-spanner==1.18.0
google-cloud-storage==1.31.2
google-cloud-translate==2.0.2
google-crc32c==1.1.2
google-resumable-media==1.3.3
googleapis-common-protos==1.53.0
greenlet==0.4.15
grpc-google-iam-v1==0.12.3
grpcio==1.39.0
grpcio-status==1.39.0
h5py==2.9.0
HeapDict==1.0.1
html5lib==1.0.1
htmlmin==0.1.12
httplib2==0.18.1
idna==2.8
ImageHash==4.2.1
imageio==2.6.0
imagesize==1.1.0
importlib-metadata==0.23
ipykernel==5.1.2
ipyparallel==6.3.0
ipython==7.8.0
ipython-genutils==0.2.0
ipython-sql==0.4.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.15.1
jeepney==0.4.1
Jinja2==2.10.3
jinja2-time==0.2.0
joblib==0.13.2
json5==0.8.5
jsonschema==3.0.2
jupyter==1.0.0
jupyter-client==5.3.5
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.3
jupyter-gcs-contents-manager==0.0.1
jupyter-highlight-selected-word==0.2.0
jupyter-http-over-ws==0.0.8
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterhub==1.0.0
jupyterlab==1.1.4
jupyterlab-git==0.11.0
jupyterlab-server==1.0.6
keyring==18.0.0
kiwisolver==1.1.0
kubernetes==18.20.0
lazy-object-proxy==1.4.2
libarchive-c==2.8
libcst==0.3.20
lief==0.9.0
llvmlite==0.29.0
locket==0.2.0
lxml==4.4.1
Mako==1.1.4
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib==3.1.1
mccabe==0.6.1
metakernel==0.27.5
missingno==0.4.3
mistune==0.8.4
mkl-fft==1.0.14
mkl-random==1.1.0
mkl-service==2.3.0
mock==3.0.5
more-itertools==7.2.0
mpmath==1.1.0
msgpack==0.6.1
multidict==5.1.0
multipledispatch==0.6.0
mypy-extensions==0.4.3
navigator-updater==0.2.1
nbclient==0.5.4
nbconvert==5.6.0
nbdime==1.0.7
nbformat==4.4.0
nest-asyncio==1.5.1
networkx==2.6.2
nltk==3.4.5
nose==1.3.7
notebook==6.0.3
numba==0.45.1
numexpr==2.7.0
numpy==1.17.2
numpydoc==0.9.1
oauth2client==4.1.3
oauthlib==3.1.0
olefile==0.46
opencv-python==4.2.0.34
openpyxl==3.0.0
overrides==6.1.0
packaging==19.2
pamela==1.0.0
pandas==1.2.5
pandas-profiling==2.9.0
pandocfilters==1.4.2
papermill==2.1.3
parso==0.5.1
partd==1.0.0
path.py==12.0.1
pathlib2==2.3.5
pathspec==0.9.0
patsy==0.5.1
pep8==1.7.1
pexpect==4.7.0
phik==0.12.0
pickleshare==0.7.5
Pillow==6.2.0
Pillow-SIMD==7.0.0.post3
pkginfo==1.5.0.1
pluggy==0.13.0
ply==3.11
portalocker==2.3.0
poyo==0.5.0
prettytable==0.7.2
prometheus-client==0.7.1
prompt-toolkit==2.0.10
proto-plus==1.19.0
protobuf==3.13.0
psutil==5.6.3
ptyprocess==0.6.0
py==1.8.0
py4j==0.10.7
pyarrow==0.15.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.3pytest-openfiles==0.4.0
pytest-remotedata==0.3.2
python-dateutil==2.8.0
python-editor==1.0.4
python-slugify==5.0.2
pytz==2019.3
PyWavelets==1.0.3
PyYAML==5.4.1
pyzmq==18.1.0
QtAwesome==0.6.0
qtconsole==4.5.5
QtPy==1.9.0
regex==2021.8.3
requests==2.26.0
requests-oauthlib==1.3.0
rope==0.14.0
rsa==4.6
ruamel-yaml==0.15.46
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.1
seaborn==0.9.0
SecretStorage==3.1.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.15.0
smmap==4.0.0
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.9.3
spark-nlp==3.2.1
spark-nlp-display==1.8
sparkmonitor-s==0.0.22
Sphinx==2.2.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.2
spyder==3.3.6
spyder-kernels==0.5.2
spylon==0.3.0
spylon-kernel==0.4.1
SQLAlchemy==1.3.9
sqlparse==0.4.1
statsmodels==0.10.1
svgwrite==1.4
sympy==1.4
tables==3.5.2
tangled-up-in-unicode==0.1.0
tblib==1.4.0
tenacity==7.0.0
terminado==0.8.2
testpath==0.4.2
text-unidecode==1.3
textwrap3==0.9.2
tomli==1.2.1
toolz==0.10.0
tornado==6.0.3
tqdm==4.62.1
traitlets==4.3.3
typed-ast==1.4.3
typing-extensions==3.10.0.0
typing-inspect==0.7.1
typing-utils==0.1.0
unicodecsv==0.14.1
uritemplate==3.0.1
urllib3==1.24.2
virtualenv==20.0.35
visions==0.5.0
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==1.2.1
Werkzeug==0.16.0
widgetsnbextension==3.5.1
wrapt==1.11.2
wurlitzer==1.0.3
xlrd==1.2.0
XlsxWriter==1.2.1
xlwt==1.3.0
yarl==1.6.3
zict==1.0.0
zipp==0.6.0

**Comment by abhishekpoonia31** [comment]
It's working fine with gs://spark-lib/pubsublite/pubsublite-spark-sql-streaming-0.1.0-with-dependencies.jar
