### ISSUE TITLE
Issue writing to Pub/Sub Lite from Databricks Runtime: 6.4 Extended Support (Scala 2.11, Spark 2.4.5)

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/java-pubsublite-spark#278]
1. Sign up for an account with [Databricks Community Edition](https://medium.com/r/?url=https%3A%2F%2Fcommunity.cloud.databricks.com) 
2. Pick Databricks Runtime: 6.4 Extended Support (Scala 2.11, Spark 2.4.5)
3. Start a cluster, install the connector jar, create a notebook. 
4. Writing a rate source to Pub/Sub Lite. 

```python
from pyspark.sql import SparkSession
from pyspark.sql.types import StringType, IntegerType, BinaryType
from pyspark.sql.functions import col, lit, udf, current_timestamp
import base64

# project_number = 
# location = 
# topic_id = 

# Load service account key 
key_file = open(
  "/dbfs/FileStore/shared_uploads/../key.json",
  "rb"
)
key = base64.b64encode(key_file.read())
key = key.decode("utf-8")

# Create rate source
sdf = spark.readStream.format("rate").option("rowsPerSecond", 1).load()

sdf = (
    sdf.withColumn("key", (sdf.value % 5).cast(IntegerType()).cast(StringType()).cast(BinaryType()))
    .withColumn("event_timestamp", sdf.timestamp)
    .withColumn("data", sdf.value.cast(StringType()).cast(BinaryType()))
    .drop("value", "timestamp")
)

sdf.printSchema()

query = (
    sdf.writeStream.format("pubsublite")
    .option(
        "pubsublite.topic",
        f"projects/{project_number}/locations/{location}/topics/{topic_id}",
    )
    # Required. Use a unique checkpoint location for each job.
    .option("checkpointLocation", "/tmp/app")
    .option("gcp.credentials.key", key) 
    .outputMode("append")
    .trigger(processingTime="1 second")
    .start()
)
```

This errors out. 
```none
java.lang.NumberFormatException: For input string: "{"0":371307}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:277)
	at scala.collection.immutable.StringOps.toLong(StringOps.scala:29)
	at org.apache.spark.sql.execution.streaming.sources.RateStreamMicroBatchReader.deserializeOffset(RateStreamMicroBatchReader.scala:135)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3$$anonfun$apply$12.apply(MicroBatchExecution.scala:489)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3$$anonfun$apply$12.apply(MicroBatchExecution.scala:475)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at org.apache.spark.sql.execution.streaming.StreamProgress.foreach(StreamProgress.scala:25)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at org.apache.spark.sql.execution.streaming.StreamProgress.flatMap(StreamProgress.scala:25)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3.apply(MicroBatchExecution.scala:475)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3.apply(MicroBatchExecution.scala:475)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:263)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:61)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:474)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:208)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:176)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:176)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:263)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:61)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:176)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:170)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:296)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:208)
```

@jiangmichaellll : "somehow the PSL offsets from the write side gets into the rate source read side"

Seemingly similar [issue](https://githubmemory.com/repo/Azure/azure-cosmosdb-spark/issues?cursor=Y3Vyc29yOnYyOpK5MjAxOC0wMy0xNVQwNTozNTozNyswODowMM4SMxVf&pagination=next&page=15)?

**Comment by tmdiep** [comment]
@anguillanneuf Sorry, I'm not too familiar with this configuration. Is this using the Pub/Sub Lite Python client library?

If so, it assumes that the message id is a numeric offset, but we changed it in ~Jun 2021 to be an opaque string (actually a generation number and offset as JSON) and then more recently in Mar 2022 to be "<generation number>,<offset>". Not sure what needs to be updated to parse this correctly.

**Comment by dpcollins-google** [comment]
Going to close- the library has been rewritten entirely since this was filed.
