### ISSUE TITLE
PubSubLite java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by jhsenjaliya** [googleapis/java-pubsublite-spark#637]
I get NoSuchMethodError while trying to read message from pubsublite using spark structured streaming application.
```
Exception in thread "pubsub-lite-futures-1" java.lang.NoSuchMethodError: 'com.google.api.gax.rpc.ApiCallContext com.google.cloud.pubsublite.internal.wire.ServiceClients.getCallContext(com.google.cloud.pubsublite.internal.wire.PubsubContext, com.google.cloud.pubsublite.internal.wire.RoutingMetadata)'
	at com.google.cloud.pubsublite.spark.PslReadDataSourceOptions.lambda$null$1(PslReadDataSourceOptions.java:139)
	at com.google.cloud.pubsublite.internal.wire.SingleConnection.<init>(SingleConnection.java:71)
	at com.google.cloud.pubsublite.internal.wire.SingleConnection.<init>(SingleConnection.java:77)
	at com.google.cloud.pubsublite.internal.wire.ConnectedSubscriberImpl.<init>(ConnectedSubscriberImpl.java:54)
	at com.google.cloud.pubsublite.internal.wire.ConnectedSubscriberImpl.<init>(ConnectedSubscriberImpl.java:33)
	at com.google.cloud.pubsublite.internal.wire.ConnectedSubscriberImpl$Factory.New(ConnectedSubscriberImpl.java:46)
	at com.google.cloud.pubsublite.internal.wire.ConnectedSubscriberImpl$Factory.New(ConnectedSubscriberImpl.java:39)
	at com.google.cloud.pubsublite.internal.wire.RetryingConnectionImpl.reinitialize(RetryingConnectionImpl.java:106)
	at com.google.cloud.pubsublite.internal.wire.RetryingConnectionImpl.lambda$doStart$0(RetryingConnectionImpl.java:94)
```

i do see the getCallContext() method with required parameter and classes are present at package ` com.google.cloud.pubsublite.internal.wire` which is available in google-cloud-pubsublite-1.12.5 jar

I also noticed another thing Upon looking at the `PartitionSubscriberFactory getSubscriberFactory()` method in `com.google.cloud.pubsublite.spark.PslReadDataSourceOptions` it indeed using different consumer
`com.google.cloud.pubsublite.SequencedMessage` vs setMessageConsumer expecting ` com.google.cloud.pubsublite.proto.SequencedMessage`

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...") : **PubSub Lite**
   General, Core, and Other are also allowed as types
2. OS type and version:
3. Java version: **11**
4.  version(s):

**Comment by dyptan** [comment]
I had the same issue. Basically transitive dependencies are missing, so you have to download a fat jar "with-dependencies.jar" and append it to Spark's classpath.

**Comment by jhsenjaliya** [comment]
I can not find pubsublite-spark-sql-streaming -- with dependency jar on maven central. but i packaged from this source and used it but it does not work. r u using latest version 1.0 ?
I actually already have bigquery with dependency and gcs connector which covers all dependencies ( gax, gax-grpc, etc....)

**Comment by jhsenjaliya** [comment]
Found the issue actually, the latest change on the pubsub java client has changed the SequencedMessage package, using `com.google.cloud:google-cloud-pubsublite:1.10.0` along with `com.google.cloud:pubsublite-spark-sql-streaming:1.0.0` works. ( as the breaking change is after 1.10.0 )
