### ISSUE TITLE
pubsublite-spark-sql-streaming doesn't run on dataproc serverless

### ISSUE THREAD

**Issue by Marcus-Rosti** [googleapis/java-pubsublite-spark#644]
#### Environment details

1. [Use 2.0 or higher for serverless](https://cloud.google.com/dataproc-serverless/docs/concepts/versions/spark-runtime-versions)
2. Use 1.0 here
3. Scala 2.13
4. spark 3.4

#### Steps to reproduce

  1. Compile a job and try to read from pub sub

#### Stack trace
```
Exception in thread "stream execution thread for [id = 91c21822-c34d-4428-b8cc-ea46a1e206ad, runId = 93028d36-79b4-4a54-bfef-90e20e000625]" java.lang.IncompatibleClassChangeError: Class com.google.longrunning.GetOperationRequest does not implement the requested interface repackaged.com.google.protobuf.MessageLite
	at com.google.cloud.pubsublite.repackaged.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.<init>(ProtoLiteUtils.java:128)
	at com.google.cloud.pubsublite.repackaged.io.grpc.protobuf.lite.ProtoLiteUtils.marshaller(ProtoLiteUtils.java:84)
	at com.google.cloud.pubsublite.repackaged.io.grpc.protobuf.ProtoUtils.marshaller(ProtoUtils.java:57)
	at com.google.longrunning.stub.GrpcOperationsStub.<clinit>(GrpcOperationsStub.java:68)
```

Thanks, best of luck!

**Comment by dpcollins-google** [comment]
Dataproc serverless is currently only intended for batch workloads, not streaming workloads https://cloud.google.com/dataproc-serverless/docs/overview

That being said, this looks to me like a dependency issue, I'm not sure how dependencies are managed properly for dataproc spark serverless, but you may need to build an uber jar, see https://cloud.google.com/blog/products/data-analytics/managing-java-dependencies-apache-spark-applications-cloud-dataproc

**Comment by medb** [comment]
The issue here is that Pub/Sub connector jar has unshaded dependencies that have conflicts with Spark 3.4 dependencies:
```
$ jar -tf /tmp/pubsublite-spark-sql-streaming-1.0.0-with-dependencies.jar | grep -v com/google/cloud/pubsublite/ | wc -l
14660
```

To fix this issue Pub/Sub Lite connector should shade/relocate its dependencies in the Pub/Sub Lite connector jar.

As a workaround, users can do this manually by including Pub/Sub Lite connector in their app jar and shading all dependencies.

**Comment by AlexisBRENON** [comment]
@Marcus-Rosti I encountered the same error on Dataproc Serverless v2.1.
Actually, reverting to dataproc serverless 2.0 fixed the bug on my side, but I'm using Pyspark, and so, don't have custom java dependencies.
Feel free to add your insights and/or workaround in [my SO post](https://stackoverflow.com/questions/77229724/how-to-use-pubsublite-spark-connector-in-custom-pyspark-container-for-dataproc-s)
